/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BailWizardRouteImport } from './routes/bail-wizard'
import { Route as JudgeAuthorityRouteImport } from './routes/judge-authority'
import { Route as LegalAidRouteImport } from './routes/legal-aid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BailWizardRoute = BailWizardRouteImport.update({
  id: '/bail-wizard',
  path: '/bail-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeAuthorityRoute = JudgeAuthorityRouteImport.update({
  id: '/judge-authority',
  path: '/judge-authority',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAidRoute = LegalAidRouteImport.update({
  id: '/legal-aid',
  path: '/legal-aid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bail-wizard': typeof BailWizardRoute
  '/judge-authority': typeof JudgeAuthorityRoute
  '/legal-aid': typeof LegalAidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bail-wizard': typeof BailWizardRoute
  '/judge-authority': typeof JudgeAuthorityRoute
  '/legal-aid': typeof LegalAidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bail-wizard': typeof BailWizardRoute
  '/judge-authority': typeof JudgeAuthorityRoute
  '/legal-aid': typeof LegalAidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bail-wizard' | '/judge-authority' | '/legal-aid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bail-wizard' | '/judge-authority' | '/legal-aid'
  id: '__root__' | '/' | '/bail-wizard' | '/judge-authority' | '/legal-aid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BailWizardRoute: typeof BailWizardRoute
  JudgeAuthorityRoute: typeof JudgeAuthorityRoute
  LegalAidRoute: typeof LegalAidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bail-wizard': {
      id: '/bail-wizard'
      path: '/bail-wizard'
      fullPath: '/bail-wizard'
      preLoaderRoute: typeof BailWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge-authority': {
      id: '/judge-authority'
      path: '/judge-authority'
      fullPath: '/judge-authority'
      preLoaderRoute: typeof JudgeAuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-aid': {
      id: '/legal-aid'
      path: '/legal-aid'
      fullPath: '/legal-aid'
      preLoaderRoute: typeof LegalAidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BailWizardRoute: BailWizardRoute,
  JudgeAuthorityRoute: JudgeAuthorityRoute,
  LegalAidRoute: LegalAidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
